### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by agayev169** [loads/molotov#130]
I am trying to run the example from the [molotov's website](https://molotov.readthedocs.io/en/stable/), and getting the following error: `OSError: [WinError 87] The parameter is incorrect`

The full error message with stack is as follows:
```
Traceback (most recent call last):
  File "C:\Users\kaghayev\PycharmProjects\test\venv\Scripts\molotov-script.py", line 33, in <module>
    sys.exit(load_entry_point('molotov==2.1', 'console_scripts', 'molotov')())
  File "c:\users\kaghayev\pycharmprojects\test\venv\lib\site-packages\molotov\run.py", line 223, in main
    return run(args)
  File "c:\users\kaghayev\pycharmprojects\test\venv\lib\site-packages\molotov\run.py", line 301, in run
    res = Runner(args)()
  File "c:\users\kaghayev\pycharmprojects\test\venv\lib\site-packages\molotov\runner.py", line 73, in __call__
    return self._launch_processes()
  File "c:\users\kaghayev\pycharmprojects\test\venv\lib\site-packages\molotov\runner.py", line 96, in _launch_processes
    p.start()
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object

(venv) C:\Users\kaghayev\PycharmProjects\molotovTest>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\kaghayev\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

My configuration is as follows:
- OS: Windows 10 x64
- Python: 3.7.0 & 3.9.1 (I tried on both and get the same error)

**Comment by tarekziade** [comment]
Thanks, I'll look at this. Could you tell me which example failed? (or  all?)

**Comment by tarekziade** [comment]
note to myself.  https://databasefaq.com/index.php/answer/114012/python-windows-multiprocessing-cherrypy-python-multiprocessing-multiprocessing-works-in-ubuntu-doesnt-in-windows

**Comment by tarekziade** [comment]
ref 2 https://stackoverflow.com/a/19363990

**Comment by agayev169** [comment]
@tarekziade after several different tries I noticed that the error occurs only when the number of processes is greater than 1. If I do not change the number of processes (`-p 1`) everything works just fine.

**Comment by tarekziade** [comment]
I tried to fix multiprocessing support on win32 by using a cleaner multiprocessing manager support, but there are so many small issues on Python itself (like https://bugs.python.org/issue35786 ) that I think for now I'll just drop `-p` support on win32. For other platform, dill seems to work well enough.

Thanks for reporting this

**Comment by agayev169** [comment]
I will try to have a look myself. 
Thank you!

**Comment by tarekziade** [comment]
one thing that should be done is add `__getstate__` and `__setstate__` support to the `Runner` class to drop the `loop` argument when the object is pickled. (see the branch I started at https://github.com/loads/molotov/tree/multiprocess_windows )
