### ISSUE TITLE
Missing quickstart/Makefile file for molotov installed via pip

### ISSUE THREAD

**Issue by arthurlogilab** [loads/molotov#43]
```
$ molostart
**** Molotov Quickstart ****

Answer to a few questions to get started...
> Target directory [.]: 
> Create Makefile [y]: 
Generating Molotov test...
…copying 'Makefile' in '.'
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/molotov/bin/molostart", line 11, in <module>
    sys.exit(main())
  File "/home/arthur/.virtualenvs/molotov/local/lib/python3.5/site-packages/molotov/quickstart/__init__.py", line 83, in main
    _copy_file('Makefile', target_dir)
  File "/home/arthur/.virtualenvs/molotov/local/lib/python3.5/site-packages/molotov/quickstart/__init__.py", line 60, in _copy_file
    shutil.copyfile(os.path.join(_HERE, name), target)
  File "/home/arthur/.virtualenvs/molotov/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/arthur/.virtualenvs/molotov/local/lib/python3.5/site-packages/molotov/quickstart/Makefile'
```

**Comment by tarekziade** [comment]
oops, it's missing from the MANIFEST.in sorry

**Comment by tarekziade** [comment]
Fixed in https://github.com/loads/molotov/commit/0a006c72af7ebf5e1b8e10a929f8b1b7564eb77e 
sorry about that. Until the next release you can 

```
pip install git+https://github.com/loads/molotov
```
