### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by mrsarm** [loads/molotov#98]
When I execute a scenario with `--statsd` option, I get:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/molotov/runner.py", line 162, in _process
    self.statsd.close()
  File "/usr/local/lib/python3.5/dist-packages/aiomeasures/clients/statsd/client.py", line 48, in close
    self.reporter.close()
  File "/usr/local/lib/python3.5/dist-packages/aiomeasures/reporters/statsd_reporter.py", line 48, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

I have installed Molotov 1.4 with virtualenv.

**Comment by tarekziade** [comment]
Can you try with 1.5 ? if it still fails, can you tell you python and aiomeasures versions

**Comment by mrsarm** [comment]
The version 1.5 isn't published yet:

```
$ pip install --upgrade molotov==1.5
Collecting molotov==1.5
  Could not find a version that satisfies the requirement molotov==1.5 (from versions: 0.1, 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.6.2, 1.0, 1.1, 1.2, 1.3, 1.4)
No matching distribution found for molotov==1.5
```

Do you want me to install from latest source?

**Comment by tarekziade** [comment]
oops, sorry yes I meant master

```sh
$ pip install https://github.com/loads/molotov/archive/master.zip
```

**Comment by mrsarm** [comment]
Same error:

```
Traceback (most recent call last):
  File "/opt/apps/py/python3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/opt/apps/py/python3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/molotov-1.5-py3.5.egg/molotov/runner.py", line 162, in _process
    self.statsd.close()
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/aiomeasures/clients/statsd/client.py", line 48, in close
    self.reporter.close()
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/aiomeasures/reporters/statsd_reporter.py", line 48, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

My current environment is:

```
$ python --version
Python 3.5.4
$ molotov --version
1.5
$ pip freeze
aiohttp==2.3.1
aiomeasures==0.5.14
async-timeout==2.0.0
chardet==3.0.4
decorator==4.1.2
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.0
molotov==1.4
multidict==3.3.0
parso==0.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
wcwidth==0.1.7
yarl==0.13.0
```

**Comment by mrsarm** [comment]
I forgot to mention that the error is launched with more than one process, and when use only one process no errors are displayed but also there is no difference in the output:

```
$ molotov -p 1 -w 2 -r 2 --statsd
**** Molotov v1.5. Happy breaking! ****
Preparing 2 workers...
OK
SUCCESSES: 4 | FAILURES: 0 | WORKERS: 0
*** Bye ***
$ molotov -p 2 -w 2 -r 2 --statsd
**** Molotov v1.5. Happy breaking! ****
Forking 2 processes
Process Process-1:LURES: 0 | WORKERS: 0
Traceback (most recent call last):
  File "/opt/apps/py/python3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/opt/apps/py/python3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/molotov-1.5-py3.5.egg/molotov/runner.py", line 162, in _process
    self.statsd.close()
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/aiomeasures/clients/statsd/client.py", line 48, in close
    self.reporter.close()
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/aiomeasures/reporters/statsd_reporter.py", line 48, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'
Process Process-2:
Traceback (most recent call last):
  File "/opt/apps/py/python3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/opt/apps/py/python3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/molotov-1.5-py3.5.egg/molotov/runner.py", line 162, in _process
    self.statsd.close()
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/aiomeasures/clients/statsd/client.py", line 48, in close
    self.reporter.close()
  File "/home/user/prj/chk-load-tests/env3.5/lib/python3.5/site-packages/aiomeasures/reporters/statsd_reporter.py", line 48, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'
[11771] Preparing 2 workers...
[11771] OK
[11772] Preparing 2 workers...
[11772] OK
SUCCESSES: 8 | FAILURES: 0 | WORKERS: 0
*** Bye ***
```

What should be the output using the `--statsd` option?

**Comment by mrsarm** [comment]
I activated the [debug option](https://github.com/etsy/statsd#debugging) `dumpMessages` in statsd, and when I launch Molotov with the `--statsd` and more than one process I don't see any activity, but if I launch it with one process, I see the events comming Ok:

```
30 Oct 15:50:56 - DEBUG: molotov.trusty-ux.GET.127.0.0.1./carts/status:0|ms
30 Oct 15:50:56 - DEBUG: molotov.trusty-ux.GET.127.0.0.1./carts/status:0|ms
```

**Comment by tarekziade** [comment]
Thanks for all the details, working on it

**Comment by tarekziade** [comment]
@mrsarm should work now, can you try? thanks!

**Comment by mrsarm** [comment]
It worked! many thanks
